services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    ports:
      - "5432:5432"
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: odoo
      DB_PASSWORD: odoo
      DB_NAME: odoo
    volumes:
      - ./odoo-addons:/mnt/extra-addons
      - odoo-data:/var/lib/odoo
    command: odoo -i base --db_host=db --db_user=odoo --db_password=odoo --database=odoo
    restart: always

volumes:
  odoo-db-data:
  odoo-data:
